global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'dvwish9214@gmail.com'
  smtp_auth_username: 'dvwish9214@gmail.com'
  smtp_auth_password: 'hlmr fncq hpme pbgr'
  smtp_require_tls: true

route:
  receiver: 'email-notifications'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'dawit.gebreyohannes.tekle@gmail.com'
        send_resolved: true
